import type { Metadata } from 'next'
import './globals.css'
import { ThemeProvider } from '@/components/theme-provider'
import { Footer } from '@/components/footer'
import { Header } from '@/components/header'
import { GoogleAnalyticsComponent } from '@/components/google-analytics'
import { AuthProvider } from '@/components/auth-context'

export const metadata: Metadata = {
  title: 'Lance - AI Collections Agent for Freelancers | Stop Chasing, Start Collecting',
  description: 'Lance is your AI-powered collections agent that politely recovers overdue invoices while protecting client relationships. Get paid 2x faster and save 8+ hours monthly.',
  generator: 'v0.dev',
  metadataBase: new URL(
    process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000'
  ),
  icons: {
    icon: '/favicon.png',
    shortcut: '/favicon.png',
    apple: '/favicon.png',
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const gaId = process.env.NEXT_PUBLIC_GA_ID

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Additional meta tags that might not be generated by Next.js */}
        <meta name="keywords" content="AI collections agent, freelancer payment recovery, overdue invoice collection, automated payment follow-up, freelancer cash flow, client payment automation, invoice collection software, freelancer business tools, payment recovery AI, automated collections, freelancer payment solutions, late payment recovery, client relationship management, freelance business automation, get paid faster, stop chasing clients, AI for freelancers, payment automation tools, invoice follow-up automation, freelancer financial tools" />
        <meta name="author" content="Lance Team" />
        <meta name="robots" content="index, follow" />
        <meta name="googlebot" content="index, follow, max-video-preview:-1, max-image-preview:large, max-snippet:-1" />
        <link rel="canonical" href="https://lanceos.ai" />
        
        {/* Additional Open Graph tags */}
        <meta property="og:image:width" content="1200" />
        <meta property="og:image:height" content="630" />
        <meta property="og:image:alt" content="Lance - Stop Chasing Invoices, Get Paid 2× Faster" />
        
        {/* Additional mobile app tags */}
        <meta name="application-name" content="Lance" />
        <meta name="apple-mobile-web-app-title" content="Lance" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="format-detection" content="telephone=no" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="msapplication-TileColor" content="#0B0F19" />
        <meta name="theme-color" content="#0B0F19" />
      </head>
      <body className="min-h-screen flex flex-col">
        <AuthProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem={false}
            disableTransitionOnChange
          >
            <div className="flex-1">
              <Header />
              {children}
            </div>
            <Footer />
          </ThemeProvider>
        </AuthProvider>
        <GoogleAnalyticsComponent gaId={gaId || ''} />
      </body>
    </html>
  )
}
